# Pandas基础命令速查清单  

## 速查表内容概要  
* [缩写解释 & 库的导入]  
* [数据的导入]  
* [数据的导出]  
* [创建测试对象]  
* [数据的查看与检查]  
* [数据的选取]  
* [数据的清洗]  
* [数据的过滤(```filter```),排序(```sort```)和分组(```groupby```)]  
* [数据的连接(```join```)与组合(```combine```)]  
* [数据的统计]

## 缩写解释 & 库的导入

**```df```** --- 任意的```pandas DataFrame```(数据框)对象      
**```s```** --- 任意的```pandas Series```(数组)对象    
```pandas```和```numpy```是用Python做数据分析最基础且最核心的库

In [56]:
import pandas as pd # 导入pandas库并简写为pd
import numpy as np # 导入numpy库并简写为np

## 数据的导入

```python  
pd.read_csv(filename) # 导入csv格式文件中的数据  
pd.read_table(filename) # 导入有分隔符的文本 (如TSV) 中的数据  
pd.read_excel(filename) # 导入Excel格式文件中的数据  
pd.read_sql(query, connection_object) # 导入SQL数据表/数据库中的数据  
pd.read_json(json_string) # 导入JSON格式的字符，URL地址或者文件中的数据  
pd.read_html(url) # 导入经过解析的URL地址中包含的数据框 (DataFrame) 数据  
pd.read_clipboard() # 导入系统粘贴板里面的数据  
pd.DataFrame(dict)  # 导入Python字典 (dict) 里面的数据，其中key是数据框的表头，value是数据框的内容。  
```

## 数据的导出

```python  
df.to_csv(filename) # 将数据框 (DataFrame)中的数据导入csv格式的文件中  
df.to_excel(filename) # 将数据框 (DataFrame)中的数据导入Excel格式的文件中  
df.to_sql(table_name,connection_object) # 将数据框 (DataFrame)中的数据导入SQL数据表/数据库中  
df.to_json(filename) # 将数据框 (DataFrame)中的数据导入JSON格式的文件中  
```

## 创建测试对象

```python  
pd.DataFrame(np.random.rand(10,5)) # 创建一个5列10行的由随机浮点数组成的数据框 DataFrame  
```

In [57]:
pd.DataFrame(np.random.rand(10,5))

          0         1         2         3         4
0  0.124700  0.628813  0.734914  0.606959  0.275290
1  0.286354  0.847413  0.129885  0.635760  0.524944
2  0.113835  0.984103  0.327450  0.303240  0.240270
3  0.871410  0.445639  0.404963  0.819988  0.895527
4  0.263007  0.316429  0.774481  0.945479  0.959037
5  0.242811  0.574332  0.267042  0.747984  0.378767
6  0.164727  0.702855  0.576954  0.558306  0.095644
7  0.557591  0.651073  0.106347  0.891804  0.519002
8  0.558277  0.115405  0.038552  0.422849  0.924860
9  0.080182  0.074334  0.540438  0.153938  0.394758

```python  
pd.Series(my_list) # 从一个可迭代的对象 my_list 中创建一个数据组  
```

In [58]:
my_list = ['Kesci',100,'欢迎来到北京天安门']
pd.Series(my_list)

0        Kesci
1          100
2    欢迎来到北京天安门
dtype: object

```python  
df.index = pd.date_range('2017/1/1', periods=df.shape[0]) # 添加一个日期索引 index  
```

In [59]:
df = pd.DataFrame(np.random.rand(10,5))
df.index = pd.date_range('2017/1/1', periods=df.shape[0])
df

                   0         1         2         3         4
2017-01-01  0.542535  0.484059  0.572176  0.024531  0.246397
2017-01-02  0.555646  0.301720  0.294391  0.199946  0.677623
2017-01-03  0.753094  0.532861  0.396000  0.531990  0.847576
2017-01-04  0.340103  0.697035  0.800694  0.051236  0.834814
2017-01-05  0.419171  0.215051  0.425898  0.803653  0.187074
2017-01-06  0.319776  0.978256  0.656594  0.375654  0.988444
2017-01-07  0.380357  0.147360  0.554098  0.655757  0.334112
2017-01-08  0.726804  0.355403  0.282017  0.218382  0.243581
2017-01-09  0.296099  0.341188  0.811050  0.531792  0.577133
2017-01-10  0.946397  0.990881  0.581074  0.307586  0.522954

## 数据的查看与检查

```python  
df.head(n)  # 查看数据框的前n行  
```

In [60]:
df = pd.DataFrame(np.random.rand(10,5))
df.head(3)

          0         1         2         3         4
0  0.291542  0.998710  0.160182  0.478401  0.724979
1  0.247730  0.366821  0.313199  0.049146  0.728211
2  0.452840  0.654712  0.092160  0.513177  0.395175

```python  
df.tail(n) # 查看数据框的最后n行  
```

In [61]:
df = pd.DataFrame(np.random.rand(10,5))
df.tail(3)

          0         1         2         3         4
7  0.273152  0.649370  0.446054  0.723653  0.257744
8  0.583844  0.769316  0.321301  0.571200  0.327061
9  0.960003  0.068261  0.321057  0.694172  0.601899

```python  
df.shape # 查看数据框的行数与列数  
```

In [62]:
df = pd.DataFrame(np.random.rand(10,5))
df.shape

(10, 5)

```python  
df.info() # 查看数据框 (DataFrame) 的索引、数据类型及内存信息  
```

In [63]:
df = pd.DataFrame(np.random.rand(10,5))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
0    10 non-null float64
1    10 non-null float64
2    10 non-null float64
3    10 non-null float64
4    10 non-null float64
dtypes: float64(5)
memory usage: 480.0 bytes

```python  
df.describe() # 对于数据类型为数值型的列，查询其描述性统计的内容  
```

In [64]:
df.describe()

               0          1          2          3          4
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.428377   0.467060   0.545944   0.420523   0.670234
std     0.298251   0.374261   0.335930   0.276951   0.263977
min     0.045371   0.032392   0.070659   0.000636   0.070008
25%     0.189695   0.114632   0.371999   0.242742   0.641682
50%     0.442809   0.426983   0.506683   0.379257   0.663770
75%     0.570645   0.840269   0.842243   0.675369   0.787764
max     0.899067   0.972386   0.981795   0.808641   0.997367

```python  
s.value_counts(dropna=False) # 查询每个独特数据值出现次数统计  
```

In [65]:
s = pd.Series([1,2,3,3,4,np.nan,5,5,5,6,7])
s.value_counts(dropna=False)

5.0    3
3.0    2
7.0    1
6.0    1
NaN    1
4.0    1
2.0    1
1.0    1
dtype: int64

```python  
df.apply(pd.Series.value_counts) # 查询数据框 (Data Frame) 中每个列的独特数据值出现次数统计  
```

## 数据的选取

```python  
df[col] # 以数组 Series 的形式返回选取的列  
```

In [66]:
df = pd.DataFrame(np.random.rand(5,5),columns=list('ABCDE'))
df['C']

0    0.611947
1    0.590414
2    0.316083
3    0.935146
4    0.406498
Name: C, dtype: float64

```python  
df[[col1, col2]] # 以新的数据框(DataFrame)的形式返回选取的列  
```

In [67]:
df = pd.DataFrame(np.random.rand(5,5),columns=list('ABCDE'))
df[['B','E']]

          B         E
0  0.375582  0.156058
1  0.137705  0.057904
2  0.230150  0.177927
3  0.783532  0.813807
4  0.437664  0.289406

```python  
s.iloc[0] # 按照位置选取  
```

In [68]:
s = pd.Series(np.array(['I','Love','Data']))
s.iloc[0]

'I'

```python  
s.loc['index_one'] # 按照索引选取  
```

In [69]:
s = pd.Series(np.array(['I','Love','Data']))
s.loc[1]

'Love'

```python  
df.iloc[0,:] # 选取第一行  
```

In [70]:
df = pd.DataFrame(np.random.rand(5,5),columns=list('ABCDE'))
df.iloc[0,:]

A    0.802522
B    0.589135
C    0.983374
D    0.879457
E    0.237612
Name: 0, dtype: float64

```python  
df.iloc[0,0] # 选取第一行的第一个元素  
```

In [71]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.iloc[0,0]

0.6201494279288515

## <center>数据的清洗</center>

```python  
df.columns = ['a','b'] # 重命名数据框的列名称  
```

In [72]:
df = pd.DataFrame({'A':np.array([1,np.nan,2,3,6,np.nan]),
                 'B':np.array([np.nan,4,np.nan,5,9,np.nan]),
                  'C':'foo'})
df.columns = ['a','b','c']
df

     a    b    c
0  1.0  NaN  foo
1  NaN  4.0  foo
2  2.0  NaN  foo
3  3.0  5.0  foo
4  6.0  9.0  foo
5  NaN  NaN  foo

```python  
pd.isnull() # 检查数据中空值出现的情况，并返回一个由布尔值(True,Fale)组成的列  
```

In [73]:
df = pd.DataFrame({'A':np.array([1,np.nan,2,3,6,np.nan]),
                 'B':np.array([np.nan,4,np.nan,5,9,np.nan]),
                  'C':'foo'})
pd.isnull(df)

       A      B      C
0  False   True  False
1   True  False  False
2  False   True  False
3  False  False  False
4  False  False  False
5   True   True  False

```python  
pd.notnull() # 检查数据中非空值出现的情况，并返回一个由布尔值(True,False)组成的列  
```

In [74]:
df = pd.DataFrame({'A':np.array([1,np.nan,2,3,6,np.nan]),
                 'B':np.array([np.nan,4,np.nan,5,9,np.nan]),
                  'C':'foo'})
pd.notnull(df)

       A      B     C
0   True  False  True
1  False   True  True
2   True  False  True
3   True   True  True
4   True   True  True
5  False  False  True

```python  
df.dropna() # 移除数据框 DataFrame 中包含空值的行  
```

In [75]:
df = pd.DataFrame({'A':np.array([1,np.nan,2,3,6,np.nan]),
                 'B':np.array([np.nan,4,np.nan,5,9,np.nan]),
                  'C':'foo'})
df.dropna()

     A    B    C
3  3.0  5.0  foo
4  6.0  9.0  foo

```python  
df.dropna(axis=1) # 移除数据框 DataFrame 中包含空值的列  
```

In [76]:
df = pd.DataFrame({'A':np.array([1,np.nan,2,3,6,np.nan]),
                 'B':np.array([np.nan,4,np.nan,5,9,np.nan]),
                  'C':'foo'})
df.dropna(axis=1)

     C
0  foo
1  foo
2  foo
3  foo
4  foo
5  foo

```python  
df.dropna(axis=0,thresh=n)  
```

In [77]:
df = pd.DataFrame({'A':np.array([1,np.nan,2,3,6,np.nan]),
                 'B':np.array([np.nan,4,np.nan,5,9,np.nan]),
                  'C':'foo'})
test = df.dropna(axis=1,thresh=1)
test

     A    B    C
0  1.0  NaN  foo
1  NaN  4.0  foo
2  2.0  NaN  foo
3  3.0  5.0  foo
4  6.0  9.0  foo
5  NaN  NaN  foo

```python  
df.fillna(x) # 将数据框 DataFrame 中的所有空值替换为 x  
```

In [78]:
df = pd.DataFrame({'A':np.array([1,np.nan,2,3,6,np.nan]),
                 'B':np.array([np.nan,4,np.nan,5,9,np.nan]),
                  'C':'foo'})
df.fillna('Test')

      A     B    C
0     1  Test  foo
1  Test     4  foo
2     2  Test  foo
3     3     5  foo
4     6     9  foo
5  Test  Test  foo

```s.fillna(s.mean())```-> 将所有空值替换为平均值

In [79]:
s = pd.Series([1,3,5,np.nan,7,9,9])
s.fillna(s.mean())

0    1.000000
1    3.000000
2    5.000000
3    5.666667
4    7.000000
5    9.000000
6    9.000000
dtype: float64

```python  
s.astype(float) # 将数组(Series)的格式转化为浮点数  
```

In [80]:
s = pd.Series([1,3,5,np.nan,7,9,9])
s.astype(float)

0    1.0
1    3.0
2    5.0
3    NaN
4    7.0
5    9.0
6    9.0
dtype: float64

```python  
s.replace(1,'one') # 将数组(Series)中的所有1替换为'one'  
```

In [81]:
s = pd.Series([1,3,5,np.nan,7,9,9])
s.replace(1,'one')

0    one
1      3
2      5
3    NaN
4      7
5      9
6      9
dtype: object

```python  
s.replace([1,3],['one','three']) # 将数组(Series)中所有的1替换为'one', 所有的3替换为'three'  
```

In [82]:
s = pd.Series([1,3,5,np.nan,7,9,9])
s.replace([1,3],['one','three'])

0      one
1    three
2        5
3      NaN
4        7
5        9
6        9
dtype: object

```python  
df.rename(columns=lambda x: x + 2) # 将全体列重命名  
```

In [83]:
df = pd.DataFrame(np.random.rand(4,4))
df.rename(columns=lambda x: x+ 2)

          2         3         4         5
0  0.199315  0.397694  0.595471  0.702042
1  0.895308  0.383657  0.924857  0.387135
2  0.501154  0.496956  0.003422  0.882996
3  0.193964  0.404243  0.095211  0.395490

```python  
df.rename(columns={'old_name': 'new_ name'}) # 将选择的列重命名  
```

In [84]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.rename(columns={'A':'newA','C':'newC'})

       newA         B      newC         D         E
0  0.006902  0.130668  0.588253  0.489699  0.828503
1  0.692030  0.713264  0.448702  0.922569  0.841647
2  0.820884  0.278975  0.973285  0.368249  0.910720
3  0.605307  0.245191  0.278977  0.930162  0.570000
4  0.210345  0.669398  0.752190  0.640480  0.560109
5  0.838045  0.490461  0.141277  0.701673  0.886979
6  0.269934  0.178593  0.925600  0.281041  0.424449
7  0.693416  0.910333  0.747005  0.129952  0.577580
8  0.488725  0.620892  0.420363  0.649112  0.005010
9  0.393920  0.361133  0.259108  0.414558  0.424067

```python  
df.set_index('column_one') # 改变索引  
```

In [85]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.set_index('B')

                 A         C         D         E
B
0.982207  0.099240  0.206860  0.710280  0.544967
0.691256  0.043547  0.177603  0.558468  0.345116
0.274112  0.974307  0.990488  0.676690  0.190155
0.756095  0.184330  0.350406  0.033724  0.819789
0.181148  0.672100  0.287498  0.663488  0.710976
0.762092  0.305976  0.829070  0.166664  0.761956
0.805011  0.552787  0.491527  0.770628  0.674635
0.483730  0.083538  0.908853  0.135441  0.559056
0.718782  0.570057  0.956017  0.641058  0.899683
0.730190  0.663991  0.770312  0.066471  0.553893

```python  
df.rename(index = lambda x: x+ 1) # 改变全体索引  
```

In [86]:
df = pd.DataFrame(np.random.rand(10,5))
df.rename(index = lambda x: x+ 1)

           0         1         2         3         4
1   0.760723  0.037883  0.512812  0.835014  0.379618
2   0.466139  0.699128  0.126892  0.878623  0.323207
3   0.935535  0.726897  0.836532  0.641972  0.763378
4   0.700320  0.349015  0.810935  0.132410  0.099193
5   0.540439  0.840218  0.248054  0.212659  0.504209
6   0.547809  0.908531  0.391702  0.938793  0.201250
7   0.892763  0.436887  0.746108  0.799222  0.670419
8   0.068700  0.332939  0.662992  0.807395  0.716419
9   0.706487  0.199435  0.047795  0.010290  0.664999
10  0.761288  0.211871  0.790216  0.946772  0.235096

## 数据的过滤(```filter```),排序(```sort```)和分组(```groupby```)

```python  
df[df[col] > 0.5] # 选取数据框df中对应行的数值大于0.5的全部列  
```

In [87]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df[df['A'] > 0.5]

          A         B         C         D         E
2  0.567295  0.292607  0.833998  0.335511  0.284481
4  0.986783  0.227339  0.602127  0.067106  0.441730
7  0.680557  0.402002  0.338391  0.938156  0.587421
9  0.612871  0.612452  0.172895  0.937389  0.554830

```python  
df[(df[col] > 0.5) & (df[col] < 0.7)] # 选取数据框df中对应行的数值大于0.5，并且小于0.7的全部列  
```

In [88]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df[(df['C'] > 0.5) & (df['D'] < 0.7)]

          A         B         C         D         E
0  0.695845  0.961018  0.517321  0.125897  0.252606
1  0.757774  0.080707  0.827550  0.455970  0.625889
4  0.236532  0.143751  0.703340  0.256056  0.417599
6  0.000862  0.300779  0.770640  0.608825  0.910808

```python  
df.sort_values(col1) # 按照数据框的列col1升序(ascending)的方式对数据框df做排序  
```

In [89]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.sort_values('E')

          A         B         C         D         E
3  0.909315  0.138012  0.893384  0.400620  0.052623
9  0.348643  0.731269  0.266170  0.149204  0.177203
0  0.419012  0.584874  0.471201  0.926117  0.208757
5  0.300400  0.914765  0.148493  0.680316  0.300798
1  0.011394  0.435946  0.137154  0.178820  0.315738
8  0.557422  0.687195  0.552951  0.340111  0.542377
4  0.424925  0.631225  0.657433  0.335010  0.552824
2  0.537014  0.756888  0.997233  0.199241  0.629951
7  0.525322  0.048543  0.213029  0.028880  0.766634
6  0.505292  0.642341  0.861355  0.162052  0.827998

```python  
df.sort_values(col2,ascending=False) # 按照数据框的列col2降序(descending)的方式对数据框df做排序  
```

In [90]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.sort_values('A',ascending=False)

          A         B         C         D         E
7  0.874108  0.348412  0.677207  0.930297  0.145702
2  0.579687  0.767142  0.397328  0.504610  0.782012
6  0.490880  0.873091  0.858417  0.135184  0.609850
9  0.489921  0.802264  0.192936  0.138327  0.683818
8  0.394221  0.579320  0.458717  0.698748  0.816357
1  0.374112  0.342755  0.826507  0.263822  0.577337
3  0.326424  0.734350  0.098251  0.207587  0.066448
4  0.300907  0.937886  0.672126  0.143273  0.774541
0  0.163986  0.604084  0.998324  0.613714  0.134914
5  0.111199  0.401648  0.914229  0.782146  0.718678

```python  
df.sort_values([col1,col2],ascending=[True,False]) # 按照数据框的列col1升序，col2降序的方式对数据框df做排序  
```

In [91]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.sort_values(['A','E'],ascending=[True,False])

          A         B         C         D         E
8  0.003553  0.469564  0.159236  0.831057  0.543121
6  0.145298  0.937633  0.008693  0.478683  0.972462
5  0.152810  0.273300  0.419870  0.701429  0.110669
1  0.390134  0.522145  0.512849  0.802782  0.933644
3  0.410062  0.036127  0.301771  0.825672  0.024897
7  0.589622  0.717424  0.259905  0.054025  0.795044
4  0.632174  0.556903  0.406005  0.395482  0.945621
9  0.671153  0.981980  0.968328  0.825165  0.900199
0  0.702016  0.624413  0.889018  0.044093  0.573164
2  0.885342  0.400266  0.767713  0.077520  0.110639

```python  
df.groupby(col) # 按照某列对数据框df做分组  
```

In [92]:
df = pd.DataFrame({'A':np.array(['foo','foo','foo','foo','bar','bar']),
      'B':np.array(['one','one','two','two','three','three']),
     'C':np.array(['small','medium','large','large','small','small']),
     'D':np.array([1,2,2,3,3,5])})

df.groupby('A').count()

     B  C  D
A
bar  2  2  2
foo  4  4  4

```python  
df.groupby([col1,col2]) # 按照列col1和col2对数据框df做分组  
```

In [93]:
df = pd.DataFrame({'A':np.array(['foo','foo','foo','foo','bar','bar']),
      'B':np.array(['one','one','two','two','three','three']),
     'C':np.array(['small','medium','large','large','small','small']),
     'D':np.array([1,2,2,3,3,5])})

df.groupby(['B','C']).sum()

              D
B     C
one   medium  2
      small   1
three small   8
two   large   5

```python  
df.groupby(col1)[col2].mean() # 按照列col1对数据框df做分组处理后，返回对应的col2的平均值  
```

In [94]:
df = pd.DataFrame({'A':np.array(['foo','foo','foo','foo','bar','bar']),
      'B':np.array(['one','one','two','two','three','three']),
     'C':np.array(['small','medium','large','large','small','small']),
     'D':np.array([1,2,2,3,3,5])})
df.groupby('B')['D'].mean()

B
one      1.5
three    4.0
two      2.5
Name: D, dtype: float64

```pythyon  
df.pivot_table(index=col1,values=[col2,col3],aggfunc=mean) # 做透视表，索引为col1,针对的数值列为col2和col3，分组函数为平均值  
```

In [95]:
df = pd.DataFrame({'A':np.array(['foo','foo','foo','foo','bar','bar']),
      'B':np.array(['one','one','two','two','three','three']),
     'C':np.array(['small','medium','large','large','small','small']),
     'D':np.array([1,2,2,3,3,5])})

df.pivot_table(df,index=['A','B'],
               columns=['C'],aggfunc=np.sum)

              D
C         large medium small
A   B
bar three   NaN    NaN   8.0
foo one     NaN    2.0   1.0
    two     5.0    NaN   NaN

```python  
df.groupby(col1).agg(np.mean)  
```

In [96]:
df = pd.DataFrame({'A':np.array(['foo','foo','foo','foo','bar','bar']),
      'B':np.array(['one','one','two','two','three','three']),
     'C':np.array(['small','medium','large','large','small','small']),
     'D':np.array([1,2,2,3,3,5])})
df.groupby('A').agg(np.mean)

     D
A
bar  4
foo  2

```python  
df.apply(np.mean) # 对数据框df的每一列求平均值  
```

In [97]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.apply(np.mean)

A    0.423827
B    0.667402
C    0.556546
D    0.573548
E    0.528149
dtype: float64

```python  
df.apply(np.max,axis=1) # 对数据框df的每一行求最大值  
```

In [98]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.apply(np.max,axis=1)

0    0.768229
1    0.981652
2    0.974897
3    0.701267
4    0.950480
5    0.540147
6    0.850355
7    0.920124
8    0.947052
9    0.999007
dtype: float64

## 数据的连接(```join```)与组合(```combine```)

```python  
df1.append(df2) # 在数据框df2的末尾添加数据框df1，其中df1和df2的列数应该相等  
```

In [99]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])

df1.append(df2)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

```python  
pd.concat([df1, df2],axis=1) # 在数据框df1的列最后添加数据框df2,其中df1和df2的行数应该相等  
```

In [100]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])
pd.concat([df1,df2],axis=1)

     A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

```python  
df1.join(df2,on=col1,how='inner') # 对数据框df1和df2做内连接，其中连接的列为col1  
```

In [101]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],           
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'key': ['K0', 'K1', 'K0', 'K1']})
   

df2 = pd.DataFrame({'C': ['C0', 'C1'],
                      'D': ['D0', 'D1']},
                     index=['K0', 'K1'])
   

df1.join(df2, on='key')

    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K0  C0  D0
3  A3  B3  K1  C1  D1

## 数据的统计

```python  
df.describe() # 得到数据框df每一列的描述性统计  
```

In [102]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.describe()

               A          B          C          D          E
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.508860   0.583492   0.456365   0.354612   0.361879
std     0.307480   0.302204   0.295955   0.313516   0.240138
min     0.050326   0.131829   0.058111   0.014080   0.003307
25%     0.346098   0.451184   0.189134   0.111645   0.200307
50%     0.436717   0.583431   0.456987   0.293326   0.382967
75%     0.775672   0.840807   0.693429   0.449521   0.465821
max     0.927452   0.958477   0.943518   0.898044   0.787660

```python  
df.mean() # 得到数据框df中每一列的平均值  
```

In [103]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.mean()

A    0.504579
B    0.390639
C    0.579542
D    0.541546
E    0.470931
dtype: float64

```python  
df.corr() # 得到数据框df中每一列与其他列的相关系数  
```

In [104]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.corr()

          A         B         C         D         E
A  1.000000  0.091478  0.200965  0.052462  0.558304
B  0.091478  1.000000 -0.343433 -0.018200  0.220165
C  0.200965 -0.343433  1.000000 -0.330816  0.142728
D  0.052462 -0.018200 -0.330816  1.000000  0.049373
E  0.558304  0.220165  0.142728  0.049373  1.000000

```python  
df.count() # 得到数据框df中每一列的非空值个数  
```

In [105]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.count()

A    10
B    10
C    10
D    10
E    10
dtype: int64

```python  
df.max() # 得到数据框df中每一列的最大值  
```

In [106]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.max()

A    0.943299
B    0.945844
C    0.967405
D    0.963771
E    0.942676
dtype: float64

```python  
df.min() # 得到数据框df中每一列的最小值  
```

In [107]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.min()

A    0.102047
B    0.115489
C    0.016219
D    0.045692
E    0.161886
dtype: float64

```python  
df.median() # 得到数据框df中每一列的中位数  
```

In [108]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.median()

A    0.502172
B    0.679359
C    0.417207
D    0.388383
E    0.379149
dtype: float64

```python  
df.std() # 得到数据框df中每一列的标准差  
```

In [109]:
df = pd.DataFrame(np.random.rand(10,5),columns=list('ABCDE'))
df.std()

A    0.369630
B    0.321507
C    0.361331
D    0.272767
E    0.272125
dtype: float64